name: webRTCDemo
description: Flutter Template
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_webrtc: ^0.2.8
  socket_io_client: ^0.9.11

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.1

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'
# To Generate icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
